### ISSUE TITLE
responsividad

### ISSUE THREAD

**Issue by carloscarcamo** [webslinder/AesiaWeb#2]
Hay que trabajar un poco en la responsividad, aca dejo unas capturas:
El boton en el header, vean las tendencias actuales para que le puedan dar un estilo más atractivo, hacer mas grande el boton puede ayudar.

![r0](https://cloud.githubusercontent.com/assets/2413746/7262692/d70657be-e838-11e4-84f9-afcbb767beb9.png)

En esta parte se mueven los elementos y no fluyen responsivamente

![r1](https://cloud.githubusercontent.com/assets/2413746/7262652/97055610-e838-11e4-82f8-623842a0768e.png)

La galeria, al ser mas pequeña la pantalla deberia mostrar menos imagenes en una linea, para mantener consistencia en la responsividad

![r2](https://cloud.githubusercontent.com/assets/2413746/7262764/48a17070-e839-11e4-8859-de7e86c20f20.png)

El formulario de contacto, esta bien lo simplista aunque se veria mejor con iconos, pero tampoco es necesario, lo que si hay que mejorar es el estilo del dialog, esta muy simple, por ejemplo delimitar bien el titlo del dialogo con los elementos del formulario, tal ves un margin:

![r3](https://cloud.githubusercontent.com/assets/2413746/7262848/038a0104-e83a-11e4-916e-099001991456.png)

El footer podria mejorar, me gusta que sea simple pero podria hacerce un poquito mas vistoso

![r4](https://cloud.githubusercontent.com/assets/2413746/7262941/af61db14-e83a-11e4-8fd3-73639ca61ef4.png)

Unos footers para inspirarse: 

![f4](https://cloud.githubusercontent.com/assets/2413746/7263069/b4b44420-e83b-11e4-9b72-0f13cc47184a.png)
![f1](https://cloud.githubusercontent.com/assets/2413746/7263065/af754e0a-e83b-11e4-846e-36e25185964d.png)
![f0](https://cloud.githubusercontent.com/assets/2413746/7263066/b12d3280-e83b-11e4-8462-09e558c606d0.png)
![f3](https://cloud.githubusercontent.com/assets/2413746/7263064/ae65f1a4-e83b-11e4-8067-a5728f964982.png)

**Comment by carloscarcamo** [comment]
Solo faltaria arreglar esta parte cuando esta en landscape
![landing](https://cloud.githubusercontent.com/assets/2413746/7304216/1ec2bc5c-e9b3-11e4-8786-d428d935891d.png)

**Comment by agodin3z** [comment]
Okok ahorita veo eso :+1:

**Comment by carloscarcamo** [comment]
fixed in commit: 469071245809f4a27a9b68add86d154532046563

**Comment by carloscarcamo** [comment]
fixed in commit: 469071245809f4a27a9b68add86d154532046563
