### ISSUE TITLE
material design

### ISSUE THREAD

**Issue by carloscarcamo** [webslinder/AesiaWeb#3]
Estan usando el tema de material design para bootstrap, más sin embargo el sitio tiene pocos elementos con material design, por ejemplo los botones y la barra de menu podrian tener el efecto waves de material design.

En la barra lateral no funcionan los links del menu.

Al moverse a una sección veo que tiene anclas a las secciones, seria bueno ponerle un fecto de scrolling para que se mueva un poco más lento.

Hace falta un boton para ir hacia arriba...

**Comment by agodin3z** [comment]
De este issue solo falta ver como se hace para que se vea el wave effect xD porque lo tiene activo pero no se nota mucho.
