### ISSUE TITLE
menubar

### ISSUE THREAD

**Issue by carloscarcamo** [webslinder/AesiaWeb#4]
Me gustaria que se mejorara un poco la barra de menus, no es que este mala sino que, desde mi punto de vista, es muy simple.

El color como que hace ver muy triste la web, UX y más UX jajaja

**Comment by carloscarcamo** [comment]
fixed in commit: 469071245809f4a27a9b68add86d154532046563

**Comment by agodin3z** [comment]
Hey aún tiene un bug el menu, cuando estas en landscape no se muestra todo por eso no hice mencion de esto xD

**Comment by carloscarcamo** [comment]
ok. arreglalo entonces jajaja!

**Comment by EnriqueV** [comment]
Se que no tiene nada que ver pero la comunidad mozilla sv sta invitada a
Honduras más tarde redactó un correo para contarles todo

**Comment by carloscarcamo** [comment]
usemos esto: https://gitter.im/webslinder

**Comment by agodin3z** [comment]
En eso estoy ahorita XD
PD: Estas herramientas son las que uso para hacer testeos de las webs:
- [Screenfly](http://quirktools.com/screenfly) para ver como se mira el sitio en distintos tamaños de pantalla.
- [woorank](https://www.woorank.com/) para el UX.
